### ISSUE TITLE
[FEATURE_REQUEST] multi-part questions

### ISSUE THREAD

**Issue by jeisner** [argolab/LLMRubric#3]
Sometimes a question may have multiple parts ("sub-questions").
In particular, it might prompt the LLM to fill out a JSON.  (Some LLMs can enforce JSON output or even specific JSON schemas.)

Some issues with this:

* The set of fields in the JSON might vary.  For example, the instructions might indicate that part B should be answered only if part A is answered "yes."  We should accommodate this to the handling of other conditional questions.

* We can extract the sub-answers to the sub-questions by parsing the JSON.  Getting the _distribution_ over alternative values of a sub-answer is trickier, though, because the JSON parser only sees the concatenated output string, and doesn't tell us that the value of field "B" was derived from a particular substring that we can identify as token 79.  We can discuss strategies on this ticket.

* When we extract a _distribution_, it is conditional on all previous tokens (chains of thought, etc.) and in particular on all previous subanswers.  Thus, it may be important for the calibrator to know what those previous tokens are.  For example, if part C returns a distribution over [1,2,3,4], that distribution is conditioned on the actual values of parts A and B, so the calibrator had better see those actual values and not just their distributions.

**Comment by Prabhav55221** [comment]
@jeisner 

Thinking about something like the below rubric structure to add this feature:

```yaml
rubric:
  Q1:
    question_id: "Q1"
    type: "structured"
    prompt: "Evaluate the response coherence and provide detailed analysis:"
    schema: {
      "is_coherent": {"type": "boolean"},
      "coherence_score": {
        "type": "integer",
        "enum": [1, 2, 3, 4, 5],
        "description": "Only required if is_coherent is true"
      },
      "reasoning": {"type": "string"}
    }
    dependencies: {
      "coherence_score": {"field": "is_coherent", "value": true}
    }
```

I would probably add indicators in fields that the LLM needs to fill specifically: The dependencies can define whether the response depends on previous answers.
